### ISSUE TITLE
Unexpected type error

### ISSUE THREAD

**Issue by hyousef-rusty** [google/evcxr#100]
I got the below error, can you help/guide:

![image](https://user-images.githubusercontent.com/60115476/72998744-65b4ca00-3e0f-11ea-934a-e11ba9f1ff02.png)

![image](https://user-images.githubusercontent.com/60115476/72998676-4e75dc80-3e0f-11ea-8b94-51cbaccc90ab.png)

**Comment by bjorn3** [comment]
I think `odbc::Result` shadowed `std::result::Result`.

**Comment by hyousef-rusty** [comment]
@bjorn3 
I tried excluding "odbc::Result" but got:

![image](https://user-images.githubusercontent.com/60115476/73000048-5afb3480-3e11-11ea-9b23-fef0d3ba9ceb.png)

**Comment by bjorn3** [comment]
Try

```rust
use odbc::*;
use std::result::Result;
```

The `use std::result::Result;` will shadow the `Result` from the glob import `use odbc::*;`.

**Comment by hyousef-rusty** [comment]
@bjorn3 
I got
```bash
     let mut env = create_environment_v3().map_err(|e| e.unwrap())?;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
```

So I replaced the `?` by `.unwrap()`

**Comment by bjorn3** [comment]
Does it work if you remove the `.map_err(|e| e.unwrap())` part?

**Comment by hyousef-rusty** [comment]
No @bjorn3 , it didn't.
![image](https://user-images.githubusercontent.com/60115476/73018609-0a94ce80-3e33-11ea-8991-06a6b063a09e.png)

**Comment by davidlattimore** [comment]
Thanks for the report. I'll change the generated code that it fully qualifies Result.

**Comment by davidlattimore** [comment]
If you'd like to try out the fix, you can install from git with:

```sh
cargo install --force --git https://github.com/google/evcxr.git evcxr_jupyter
```
