### ISSUE TITLE
the name `evcxr_send_text_plain` is defined multiple times

### ISSUE THREAD

**Issue by timthelion** [google/evcxr#101]
If you scroll down to the end of this document you'll see the error:
[multiple-times.zip](https://github.com/google/evcxr/files/4143232/multiple-times.zip)

Restarting kernel did not help.

**Comment by timthelion** [comment]
Putting that block into curly brackets (it's own scope) fixes things.

**Comment by davidlattimore** [comment]
Thanks for reporting that. I am able to reproduce. I've cut down to a smaller example:

```rust
for a in 1..2 {
}
5
```

It looks like evcxr is getting confused and thinks it needs to print the result of evaluating the loop, as well as the number 5. Hopefully shouldn't be too hard to fix, but I'm out of time for today.

In the meantime, you can work around it by adding a semicolon after your loops. e.g.

```rust
for a in 1..2 {
};
5
```

**Comment by timthelion** [comment]
Great, thanks for cutting that down to size. I wanted to do that, but it just seemed so mysterious, I didn't know where to start. Did you do it by bisection/trial and error or is there some way to see some intermediate representation that would help debug these sorts of things?

**Comment by davidlattimore** [comment]
Trial and error. I started by rewriting it to not use any external crates, then cut out bits of code a bit at a time, rerunning after each cut to confirm that it still reproduced.

**Comment by davidlattimore** [comment]
Just pushed a fix to github. If you want to try it out, there are instructions for installing from HEAD in the README.

BTW, it's great seeing evcxr being used for doing graph stuff :)

**Comment by timthelion** [comment]
Great, thanks for the fast fix :)
