### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by skade** [google/evcxr#104]
The README contains the following phrase:

> If you think you'd like a REPL, I'd definitely recommend checking our the Jupyter kernel.

I'm sure it should say "checking out the".

Filed here instead of #103, I'm not signing a legal document over fixing you a typo ;).

**Comment by davidlattimore** [comment]
@skade completely understand about not wanting to sign a legal document over fixing a typo and apologies. Unfortunately my employer doesn't give me any choice in the matter.

**Comment by davidlattimore** [comment]
Oh, and thanks for pointing out the typo :)
