### ISSUE TITLE
"Unhandled pat kind" for wildcard/rest patterns

### ISSUE THREAD

**Issue by dima74** [google/evcxr#108]
When using wild (`_`) or rest (`..`) patterns in let assignment, the "Unhandled pat" error is printed:

```
>> let _ = 1;
Unhandled pat kind: Wild(PatWild { attrs: [], underscore_token: Underscore })
>> let (x, ..) = (1, 2, 3);
Unhandled pat kind: Rest(PatRest { attrs: [], dot2_token: Dot2 })
```

It is related to `record_new_locals` function:
https://github.com/google/evcxr/blob/f7050ef088b5d9b297c92cd86b087f6ddd527161/evcxr/src/eval_context.rs#L929

**Comment by davidlattimore** [comment]
Thanks for pointing that out. Looks like despite the print statement, the code was being executed as expected. I'll remove the print statement. I also added a test to make sure that the code was handled properly.
