### ISSUE TITLE
evcxr's variable shadowing differs from Rust

### ISSUE THREAD

**Issue by tos-kamiya** [google/evcxr#109]
I've found that variable shadowing (by the same name variable) differs between `evcxr` and `rustc`.

The following code can be compiled without error with `rustc`:

```rust
fn main() {
    let mut s = String::new();
    s += "abc";
    let s = &s;
    println!("s={}", s);
}
```

However, the following code occurs an error in `evcxr`:

```
Welcome to evcxr. For help, type :help
>> let mut s = String::new();
>> s += "abc";
>> let s = &s;
           ^^ borrowed value does not live long enough
`s` does not live long enough
Values assigned to variables in Evcxr cannot contain references (unless they're static)
```

Is this behavior intended by design?

**Comment by tos-kamiya** [comment]
Sorry, I will withdraw this issue.

It is not a problem of variable shadowing, but rather related to reference, because the following code also emits the same error:

```
Welcome to evcxr. For help, type :help
>> let mut s = String::new();
>> s += "abc";
>> let t = &s;
           ^^ borrowed value does not live long enough
`s` does not live long enough
Values assigned to variables in Evcxr cannot contain references (unless they're static)
           ^^ borrow of `s` occurs here
cannot move out of `s` because it is borrowed
```

**Comment by tos-kamiya** [comment]
FYI: I've found the above code can run on evcxr's repl, by explicitly adding a scope {....},
though this trick does not seem explained in documents [evcxr repl README](https://github.com/google/evcxr/blob/master/evcxr_repl/README.md), [evcxr jupyter](https://github.com/google/evcxr/tree/master/evcxr_jupyter), [evcxr jupyter sample](https://github.com/google/evcxr/blob/master/evcxr_jupyter/samples/evcxr_jupyter_tour.ipynb) .

```
>> {
let mut s = String::new();
s += "abc";
let s = &s;
println!("s={}", s);
}
s=abc
()
```

**Comment by davidlattimore** [comment]
Thanks. That's a good suggestion to document using a scope if you don't need the variable to be preserved. I could probably just add that to the error message. The other option would be to allow the code to be run, but not preserve the variable. Not sure if that might be confusing though.
