### ISSUE TITLE
Use #[derive(Debug)] to display struct

### ISSUE THREAD

**Issue by korakot** [google/evcxr#112]
I follow the rust book. There's a part where we can display a struct automatically using #[derive(Debug)], but I cannot do it in evcxr_jupyter.

```rust
#[derive(Debug)]
struct Point {
    x: i32,
    y: i32,
}
let p = Point {x: 0, y: 0};
p
```
Here's the error.
```
p
^ `Point` cannot be formatted using `{:?}`
`Point` doesn't implement `std::fmt::Debug`
```

Maybe I misunderstand something. 

How can I display the Point without manually defining `impl fmt::Debug for Point`?

**Comment by thomcc** [comment]
This does work, but not if you put the #[derive(...)] on a different line than the struct -- We don't properly handle line breaks in all cases (in general, unless there's an unclosed bracket, the line break won't work.

So the following works:

```
>> #[derive(Debug)] struct Point {
    x: i32,
    y: i32,
}
>> let p = Point { x: 3, y: 4 };
>> p
Point { x: 3, y: 4 }
```

Probably better integration with parsing infrastructure (ra-syntax or similar) could help here.

**Comment by korakot** [comment]
I am using Google Colab notebook.

This works.

    #[derive(Debug)] struct Point {x: i32, y: i32}

But if the closing bracket is on a different line, it won't work

    #[derive(Debug)] struct Point {x: i32, y: i32,
    }

Error:

    unexpected close delimiter: `}`

Thanks for the solution for now.

Here's my contribution. Method to use rust in Colab with evcxr_jupyter.

https://bit.ly/colabrust

**Comment by thomcc** [comment]
Oh sorry, I thought you were using the REPL, and my comment doesn't apply outside of that.

**Comment by davidlattimore** [comment]
I tried the code from the first comment in a Jupyter notebook and it compiled and ran without error. Perhaps I missed something else that contributed to the error?

**Comment by davidlattimore** [comment]
I just tried out that Colab notebook. Nice!

I still wasn't able to reproduce the bug in that though

**Comment by korakot** [comment]
I test it again. And it works now. (though it didn't work then)

Thanks anyway. 🙏
