### ISSUE TITLE
Corrupted error messages in latest v0.5.0 on Windows

### ISSUE THREAD

**Issue by MirkoCovizzi** [google/evcxr#114]
Version: 0.5.0
CPU: Ryzen 1700
OS: Windows 10
Toolchain: x86_64-pc-windows-msvc

How to recreate the error:

1. Install evcxr: `cargo install evcxr`
2. Wait for the REPL to load completely
3. Write something that is not valid Rust, for example `error`
4. Corrupted error messages will appear, with consistent behavior

Example:

```
C:\Users\Mirko\Desktop>evcxr
Welcome to evcxr. For help, type :help
>> error
   [91m^^^^^[0m [94mnot found in this scope[0m
[91mcannot find value `error` in this scope[0m
>>
```

**Comment by davidlattimore** [comment]
Thanks for the report. Do you know if it worked OK on a previous version? I unfortunately don't have a way to test on Windows.

**Comment by bjorn3** [comment]
This is likely https://github.com/mackwic/colored/issues/59. What you see is not corruption, but uninterpreted ansi escape codes, which are used on unix to for example give colors to the terminal output.

**Comment by MirkoCovizzi** [comment]
Never used it before recently (installed thanks to the new JetBrains Rust REPL integration).

If someone can't point me in some direction I could try to find a way to fix it and make a PR.

**Comment by MirkoCovizzi** [comment]
@bjorn3 

Yep, that's it. In a Python codebase I hardcoded this to achieve that effect (also on Windows)

Red:
FAIL = '\033[91m'

**Comment by MirkoCovizzi** [comment]
A way to enable this functionality is by calling the Windows function `system` passing the command we want, in this case the const char* command `"color"`. Then, every print with ansi escape codes should work normally. At least it does in Python (just tested).

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/system-wsystem?view=vs-2019

**Comment by davidlattimore** [comment]
I'm definitely happy to provide assistance if you'd like to try to fix this. Thanks! I'll make some assumptions, but if anything isn't sufficiently clear, or you'd like more detail, please ask.

If you start by doing a git clone of the evcxr repository, then cargo build. You should then be able to run target/debug/evcxr (possibly with \ on windows I guess). There is one recently merged PR that might be relevant - 36ab39320fa946532e0574c7af00345049b16888 - it's not yet in a release.

**Comment by MirkoCovizzi** [comment]
Thank you!

**Comment by MirkoCovizzi** [comment]
@davidlattimore Made a PR with a fix! Please, let me know if there are any changes to make!
