### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by chenjianxin** [google/evcxr#119]
os: windows 10
```
:dep tokio = {version = "0.2.21", features = ["full"]}

let mut stream : tokio::net::TcpStream = tokio::net::TcpStream::connect("127.0.0.1:6543").await?;
use tokio::io::AsyncWriteExt;
stream.write(b"Hello, world!\n").await?;
```

and it return:

No connection could be made because the target machine actively refused it. (os error 10061)

**Comment by davidlattimore** [comment]
It sounds like there's no program listening on port 6543 on your computer. On Linux I'd use netcat to listen on a TCP port. Not sure what to use on windows. I'm guessing you're just wanting to experiment with async await?
