### ISSUE TITLE
Compilation error in std::io::Error::get_ref

### ISSUE THREAD

**Issue by catleeball** [google/evcxr#124]
When attempting to [get_ref()](https://doc.rust-lang.org/std/io/struct.Error.html#method.get_ref) from std::io::Error, I encountered this compilation error, and am able to reproduce it:

```
>> let er = std::fs::rename("/tmp/foo", "/tmp/bar");
>> let err = er.unwrap_err();
>> err.kind()
NotFound
>> err
Os { code: 2, kind: NotFound, message: "No such file or directory" }
>> let r = err.get_ref();
A compilation error was found in code we generated.
Ideally this should't happen. Type :last_error_json to see details.
error: ambiguous `+` in a type
   --> src/lib.rs:125:58
    |
125 | evcxr_variable_store.put_variable::<std::option::Option<&dyn std::error::Error + std::marker::Send + std::marker::Sync>>(stringify!(r), r);
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use parentheses to disambiguate: `(dyn std::error::Error + std::marker::Send + std::marker::Sync)`


>> :last_error_json
{"rendered":"error: ambiguous `+` in a type\n   --> src/lib.rs:125:58\n    |\n125 | evcxr_variable_store.put_variable::<std::option::Option<&dyn std::error::Error + std::marker::Send + std::marker::Sync>>(stringify!(r), r);\n    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use parentheses to disambiguate: `(dyn std::error::Error + std::marker::Send + std::marker::Sync)`\n\n","children":[{"children":[],"code":null,"level":"help","message":"use parentheses to disambiguate","rendered":null,"spans":[{"byte_end":4822,"byte_start":4761,"column_end":119,"column_start":58,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":125,"line_start":125,"suggested_replacement":"(dyn std::error::Error + std::marker::Send + std::marker::Sync)","suggestion_applicability":"MachineApplicable","text":[{"highlight_end":119,"highlight_start":58,"text":"evcxr_variable_store.put_variable::<std::option::Option<&dyn std::error::Error + std::marker::Send + std::marker::Sync>>(stringify!(r), r);"}]}]}],"code":null,"level":"error","message":"ambiguous `+` in a type","spans":[{"byte_end":4822,"byte_start":4761,"column_end":119,"column_start":58,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":125,"line_start":125,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":119,"highlight_start":58,"text":"evcxr_variable_store.put_variable::<std::option::Option<&dyn std::error::Error + std::marker::Send + std::marker::Sync>>(stringify!(r), r);"}]}]}

>> :version
0.5.1
```

Build info:
- Built at head: commit 66fbfda09149728fa5b7c6db757441dd75859bb7
- `cargo build --release`
- Rust v1.44.1
- RUSTFLAGS: `-C target-cpu=native -C target-feature=+aes,+f16c,+pclmul,+popcnt,+sse4.2,+sse4.1,+sse3,+sse2,+sse,+ssse3,+mmx,+avx2,+avx,+fma -C opt-level=3 -C inline-threshold=512`
  - I rebuilt this with `--release` after unsetting my rustflags and still encountered the same issues above

This was built on a corp workstation running the corp linux kernel. Please email me int@ if you need more environment specifics.

Please let me know if there's any additional info you need to debug this!

**Comment by davidlattimore** [comment]
Thanks for the report. It looks like the compiler says that the type of the variable is `std::option::Option<&dyn std::error::Error + std::marker::Send + std::marker::Sync>`, but then when we try to use that type, it says we need to put parenthesis in.

Unfortunately the initial error doesn't seem to have an error code, which makes identifying this case somewhat less reliable. I'll have to think about how to fix that.

Note though, that once fixed, the correct behaviour will be for evcxr to report that it doesn't support storing references in variables.

**Comment by davidlattimore** [comment]
I've improved the error reporting a little. Unfortunately there's not much else that can be done here, since the way evcxr currently works, it can't persist references. Perhaps some day. I'll close this for now. Thanks for the report.
