### ISSUE TITLE
Expose special `:` commands to Jupyter

### ISSUE THREAD

**Issue by jonasbb** [google/evcxr#13]
I love this project and it already works surprisingly well.

So far only `:vars` is documented to be used in a Jupyter notebook. However, all the other special `:`-commands also work and are quite useful. But `:vars` is the only command shown in the Jupyter notebook, all the others only print to the terminal.
It would be great if the other commands would also show their output in the Jupyter notebook, e.g., to see the output of `:help`.

**Comment by davidlattimore** [comment]
Ooops. Thanks for pointing that out. They used to work from Jupyter. Originally evcxr ran everything in one process and the jupyter kernel redirected its own stdout and stderr to pipes that it then read from and passed back to Jupyter. I switched to using a separate process shortly before releasing evcxr, which mean that things printed by the parent process no longer go back to Jupyter. I'll look at fixing it.
