### ISSUE TITLE
Vi mode?

### ISSUE THREAD

**Issue by aminroosta** [google/evcxr#130]
rustyline's has support for `Vi` edit_mode.
basically `<esc>` puts you in `vi` mode, `k` and `j` move in history, and the usual movement keys `h`, `l`, `^`, `$` work.

Almost the same thing as bash does 
https://spin.atomicobject.com/2011/03/29/vi-editing-mode-for-bash/

I tried this snippet, and it works. 

```
    let config = rustyline::Config::builder()
        .history_ignore_space(true)
        .edit_mode(rustyline::EditMode::Vi)
        .keyseq_timeout(0) // https://github.com/kkawakam/rustyline/issues/371
        .build();
    let mut editor = Editor::<EvcxrRustylineHelper>::with_config(config);
```

@davidlattimore do you think it's reasonable to make it the default?

**Comment by thomcc** [comment]
I would be opposed to this -- Not only because I use the emacs keybindings, but they're much closer to what people expect as defaults...

**Comment by aminroosta** [comment]
Thanks @thomcc, Despite my obvious bias, I actually agree :-)

A flag makes more sense here - `evcxr --edit-mode vi` or `evcxr --edit-mode emacs`, default remains `emacs`.
I'll try to open a PR for it.

**Comment by thomcc** [comment]
@aminroosta If you made it a `:edit-mode vi` you could put it in your init.evcxr and have it start up that way always.

That said, right now the REPL doesn't processes commands like that -- they're processed in the backend.
