### ISSUE TITLE
Variables in same scope have different lifetimes.

### ISSUE THREAD

**Issue by timthelion** [google/evcxr#145]
I'm not sure how to get around this. Here is an example:

https://github.com/timthelion/petgraph-fsm/blob/evxcr-lifetimes/readme.ipynb

In the 6th cell you will find two variables, `toaster` and `toaster_sm`. They are in the same scope, but they have different lifetimes. How can I work around this? Of course I can create a new scope and make it so `toaster_sm` does not live past the end of the cell. But then I cannot use `toaster_sm` in the cells that follow.

**Comment by bjorn3** [comment]
`toaster` is on the stack. It can be freely moved into the map storing all locals between notebook cells. However you then try to borrow from `toaster` and store that in another variable. This makes it impossible to move `toaster` into the locals map. Because of this, it will be dropped when the notebook cell ends. This isn't allowed however as the borrow is kept alive by storing the borrowing value in the locals map.

**Comment by timthelion** [comment]
Thanks for the explanation. Is there any way that I can work around this? It would be awesome to be able to redraw the state machine's state over a series of cells. Which means that I need to have the state machine persist across cell boundaries.

**Comment by bjorn3** [comment]
If you are fine with a memory leak you could try `let toaster = Box::leak(Box::new(toaster))`.

**Comment by timthelion** [comment]
Thanks for your help. The memory leak doesn't matter, it's just a README ;).  Unfortunately evcxr doesn't like that formulation either.

```
let mut toaster_sm = mktoaster(toaster_box);
                               ^^^^^^^^^^^ immutable borrow occurs here
let mut toaster_sm = mktoaster(toaster_box);
                     ^^^^^^^^^^^^^^^^^^^^^^ argument requires that `*toaster_box` is borrowed for `'static`
cannot borrow `*toaster_box` as mutable because it is also borrowed as immutable


```

**Comment by timthelion** [comment]
So I figured it out. The trick is not to name the leaky box. Perhaps this should be documented.

evcxr jupyter is awesome! Now I can visualize the state of my state machine after each input!

https://github.com/timthelion/petgraph-fsm/blob/50e5f020d88053c4b02919926c839d0ec3c5d078/readme.ipynb

**Comment by davidlattimore** [comment]
Thanks @timthelion  for the feedback and thanks @bjorn3 for the suggestion of leaking. That works quite well. I've added some documentation. I also refactored the documentation slightly to avoid duplication between the Jupyter kernel and the repl.
