### ISSUE TITLE
jupyter kernel install path issue on Mac

### ISSUE THREAD

**Issue by sidkang** [google/evcxr#164]
The issue:
```
# ENV
export JUPYTER_CONFIG_DIR="$HOME/.config/jupyter"

# install kernel
brew install zeromq pkg-config
cargo install evcxr_jupyter --no-default-features
evcxr_jupyter --install
```
The kernel is then installed into '~/.config/jupyter/kernels', and the jupyter lab cannot the identify the kernel. I have to manually move the kernel into the right location.

```
> cp -r ~/.config/jupyter/kernels/rust  /Users/sid/Library/Jupyter/kernels/

>  jupyter kernelspec list
Available kernels:
  julia-1.5    /Users/sid/Library/Jupyter/kernels/julia-1.5
  rust         /Users/sid/Library/Jupyter/kernels/rust
  python3      /Users/sid/.config/pyenv/versions/3.9.1/envs/abc/share/jupyter/kernels/python3

**Comment by davidlattimore** [comment]
Thanks for the feedback @sidkang 

The kernel was installed under `~/.config/jupyter` because you had JUPYTER_CONFIG_DIR set to that directory. I'm guessing perhaps you had that variable set when installing the kernel, but not when running `jupyter notebook`? Why did you set JUPYTER_CONFIG_DIR? Was it because you wanted to use a non-standard location for jupyter kernels?

**Comment by sidkang** [comment]
@davidlattimore Hi, I set the JUPYTER_CONFIG_DIR path to keep personal configs persistent in the ~/.config path which will sync among all my devices. I think maybe the default jupyter kernel path on Mac is $USER/Library/Jupyter/kernels. I've installed R's and Julia's kernel recently, they both just works.

**Comment by davidlattimore** [comment]
Thanks for the explanation. I think you're right that I probably shouldn't be using JUPTYER_CONFIG_DIR. I'm not sure why I used it and I can't find any documentation to suggest that I should be using it in the way that I am, so I'll remove its use.
