### ISSUE TITLE
Does not appear to be compatible with target specific directories.

### ISSUE THREAD

**Issue by photex** [google/evcxr#168]
Howdy! Because I do a lot of cross-platform and cross-arch work I specify a default target in both Windows and WSL

```toml
[build]
target = "x86_64-unknown-linux-gnu"
```

```toml
[build]
target = "x86_64-pc-windows-msvc"
```

But when I just tried to run a `println!("Howdy");` to test evcxr_jupyter, I get the following error:

```json
{
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "output_type": "error",
     "ename": "Error",
     "evalue": "Error copying '\"C:\\\\Users\\\\phote\\\\AppData\\\\Local\\\\Temp\\\\.tmpioOxBl\\\\target\\\\debug\\\\deps\\\\ctx.dll\"' to '\"C:\\\\Users\\\\phote\\\\AppData\\\\Local\\\\Temp\\\\.tmpioOxBl\\\\target\\\\debug\\\\deps\\\\code_2.dll\"': The system cannot find the file specified. (os error 2)",
     "traceback": [
      "Error copying '\"C:\\\\Users\\\\phote\\\\AppData\\\\Local\\\\Temp\\\\.tmpioOxBl\\\\target\\\\debug\\\\deps\\\\ctx.dll\"' to '\"C:\\\\Users\\\\phote\\\\AppData\\\\Local\\\\Temp\\\\.tmpioOxBl\\\\target\\\\debug\\\\deps\\\\code_2.dll\"': The system cannot find the file specified. (os error 2)"
     ]
    }
   ],
   "source": [
    "println!(\"Howdy!\");"
   ]
  }
``` 

As expected I see a target specific directory: 

```
C:/projects/LearnDSP via 🅒 LearnDSP
❯ ls C:\Users\phote\AppData\Local\Temp\.tmpioOxBl\target\

    Directory: C:\Users\phote\AppData\Local\Temp\.tmpioOxBl\target

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          25/04/2021    14:26                debug
d----          25/04/2021    14:26                x86_64-pc-windows-msvc
-a---          25/04/2021    14:26           2156 .rustc_info.json
-a---          25/04/2021    14:26            177 CACHEDIR.TAG
```

And indeed the ctx.dll is there:

```
C:/projects/LearnDSP via 🅒 LearnDSP
❯ ls C:\Users\phote\AppData\Local\Temp\.tmpioOxBl\target\x86_64-pc-windows-msvc\debug\

    Directory: C:\Users\phote\AppData\Local\Temp\.tmpioOxBl\target\x86_64-pc-windows-msvc\debug

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          25/04/2021    14:26                .fingerprint
d----          25/04/2021    14:26                build
d----          25/04/2021    14:26                deps
d----          25/04/2021    14:26                examples
d----          25/04/2021    14:26                incremental
-a---          25/04/2021    14:26              0 .cargo-lock
-a---          25/04/2021    14:26            146 ctx.d
-a---          25/04/2021    14:26           9728 ctx.dll
-a---          25/04/2021    14:26            889 ctx.dll.exp
-a---          25/04/2021    14:26           1688 ctx.dll.lib
-a---          25/04/2021    14:26         364544 ctx.pdb
```

**Comment by davidlattimore** [comment]
Thanks for the report @photex. I was able to reproduce this by putting the build configuration you specified in `~/.cargo/config.toml`. I'm unsure how to fix that though. I'd need a way to tell cargo to ignore `.cargo/config.toml`, but there doesn't seem to be such an option at present.

Have you considered putting your cross-compilation configuration in the directory for the project(s) you're working in rather than making it global? e.g. if all your projects are in subdirectories of a `work` directory, you could put a `.cargo/config.toml` in that directory and it would apply to everything under that directory.

**Comment by photex** [comment]
So far I have a lot of personal tooling and so on that expects this target directories. The default global config provides a certain convenience.

My personal option is that the target should always be there without a config as it's certainly more explicit etc. But here we are.

Is there perhaps a way to check which target triple is being used to build? I'm too new to this project to understand how it's working, but if you're able to know the target triple (via a cargo var perhaps) then maybe it's possible to search two folders for the output instead of one?

**Comment by bjorn3** [comment]
Could evcxr simply always pass `--target` to cargo and expect the corresponding target dir layout.

**Comment by photex** [comment]
One thing I haven't checked is whether I can override the global config and specify the default target for this repo. Wouldn't help me with work repos but maybe it's an option for other cases.
