### ISSUE TITLE
evcxr-repl: Question about Speed

### ISSUE THREAD

**Issue by heeh** [google/evcxr#178]
Thanks for the great work.
I know this is discussed on #52, but I just want to know why `evcxr_repl` is slower than python repl.
What are the challenges and what needs to be done?

**Comment by thomcc** [comment]
If you mean startup time, some recent PRs (such as https://github.com/google/evcxr/pull/174) help here.

For everything else, the bottleneck is Rust compilation time. Rust is very fast when running, but slow to compile. For most code, you compile once and run many times. For code in a repl, you compile once and run once, so you pay that cost for each line. There's not much that can be done other than making rustc faster.

**Comment by heeh** [comment]
Thank you for explanation @thomcc . I will close this.
