### ISSUE TITLE
evcxr_repl install fails

### ISSUE THREAD

**Issue by alanhkarp** [google/evcxr#18]
When I run 
<pre>
cargo install evcxr_repl
</pre>
on my Mac running High Sierra version 10.13.6, the build fails with
<pre>
error[E0046]: not all trait items implemented, missing: `description`
   --> /Users/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/evcxr-0.1.2/src/errors.rs:314:1
    |
314 | impl std::error::Error for Error {}
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `description` in implementation
    |
    = note: `description` from trait: `fn(&Self) -> &str`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0046`.
error: failed to compile `evcxr_repl v0.1.2`, intermediate artifacts can be found at `/var/folders/9t/_qss6y9544v29s4y30lkz5jr0000gn/T/cargo-install5FRvBt`

Caused by:
  Could not compile `evcxr`.

To learn more, run the command again with --verbose.
</pre>
I am running
<pre>
cargo 1.26.0-nightly (008c36908 2018-04-13)
</pre>
One clue to the problem is that I am using the Failure crate, which has its own Error trait.

**Comment by davidlattimore** [comment]
Thanks. It looks like a old version of cargo, which will mean an old version of rustc. In our previous email thread you said you'd upgraded, but perhaps at some point you've set the default to a specific version via rustup. Could you try having a play with rustup and see if you can get it so that cargo version reports 1.29.1?

**Comment by dwijnand** [comment]
See https://github.com/rust-lang-nursery/rustup.rs#override-precedence

Have a look at `rustup show`, and try:

* `rustup override unset` to remove the override in the current directory
* unsetting the `RUSTUP_TOOLCHAIN` env var
* remove a local `rust-toolchain` file in your project

**Comment by HadrienG2** [comment]
As an extra sanity check, you may want to check if you are actually using the version of rustc from rustup, via `which rustc`.

**Comment by davidlattimore** [comment]
Other things you might try:
rustup override list
(to see what overrides are active)
rustup show
(show installed toolchains including which is default)

**Comment by alanhkarp** [comment]
I did have overrides, but removing them didn't help.

$ rustup override list
no overrides

$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.29.1 (b801ae664 2018-09-20)

$ which rustc
/usr/local/bin/rustc

$ rustc --version
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)

Aaarrrggghhh!!!
--------------
Alan Karp

**Comment by alanhkarp** [comment]
I unset the overrides.

The RUSTUP_TOOLCHAIN env var isn't set.

I don't have a rust-toolchain in my project.

My path does have /usr/local/bin/rustc
before /Users/alan/.rustup/toolchains/stable-x86_64-apple-darwin/bin, but
rustc isn't found when I rename the one in /usr/local/bin.  Shouldn't it
have found the one in my .rustup directory?  That one is 1.29.1.

Forgive me.  I haven't touched Unix since before there was a Linux.

--------------
Alan Karp

**Comment by alanhkarp** [comment]
All fixed.  It was a path problem caused by having an environment variable
set incorrectly.  I now have the repl running.

Thanks for all your help.

--------------
Alan Karp

**Comment by alanhkarp** [comment]
Yes.  I am happily using evcxr.  The problem, a bad entry in my path, was
entirely on my end.

--------------
Alan Karp
