### ISSUE TITLE
"Initialization failed: Error renaming ..." when evcxr-repl initialized

### ISSUE THREAD

**Issue by ileixe** [google/evcxr#192]
My env
```
rust$ evcxr --version
evcxr 0.11.0

rust$ rustc --version
rustc 1.53.0 (53cb7b09b 2021-06-17)

```

When I started evcxr,
```
rust$ /home/ys/.cargo/bin/evcxr
Welcome to evcxr. For help, type :help
>> 

Initialization failed: Error renaming '"/tmp/.tmp64Ualv/target/debug/deps/libctx.so"' to '"/tmp/.tmp64Ualv/target/debug/deps/libcode_1.so"': No such file or directory (os error 2)
```

Repl terminated right away. I found if I delete `~/.cargo/config.toml`, it works fine. 

Here is my config.toml below
```
[build]
incremental = true
target = "x86_64-unknown-linux-gnu"
```

**Comment by bjorn3** [comment]
Your config.toml causes the compiled file to end up in `target/x86_64-unknown-linux-gnu/debug/deps/libctx.so` instead of `target/debug/deps/libctx.so` as evcxr expects.

**Comment by ileixe** [comment]
@bjorn3 Thanks for the explanation. Do you have any suggestions to workaround it? I don't think it's sustainable to change config every time that I run repl.

**Comment by davidlattimore** [comment]
What's the reason for needing to specify a target in your global cargo config?

**Comment by ileixe** [comment]
It's just a kind of a workaround to avoid some build conflict in-house.

**Comment by davidlattimore** [comment]
I can think of a few ways this might be fixed.

- One option would be to add a config option to evcxr that allows the target to be specified. If supplied, that could then be used to produce an appropriate path in the target directory.
- We could attempt to parse ~/.config/cargo.toml ourselves to figure out the target.
- We could try to get support added to cargo to have a flag (or metadata) that tells you the current target and/or the output filename.
- We could make evcxr detect that the file it's looking for doesn't exist, then iterate through other directories to find it. This feels a little bit hacky, but is probably the easiest to implement.

I'll probably not get to any of these all that soon, although hopefully eventually. If anyone wanted this fixed enough to have a go, I'm very happy to provide any guidance that might be useful.

**Comment by bjorn3** [comment]
You could always pass `--target` to cargo. `rustc -vV` gives the host triple after `host:`. I believe `--target` overrides `.cargo/config.toml`.

**Comment by davidlattimore** [comment]
Thanks @bjorn3 - I wasn't aware of that flag to rustc. That definitely made things much easier. I've just uploaded a fix.
