### ISSUE TITLE
"undefined symbol" when using pyo3 inside evcxr

### ISSUE THREAD

**Issue by jonasbb** [google/evcxr#201]
I wanted to use PyO3 (Python bindings) inside evcxr and noticed that in some situations this results in an error "undefined symbol" when Python tries to load a dynamic library. I first reported the issue here https://github.com/PyO3/pyo3/issues/2000 but was advised to also ask here. I am mainly interested is this is supposed to work or unsupported. The pyo3 issue contains more information about my setup.

Executing some Python code via PyO3 works fine, for example `1 + 2 + 3` or `import sys`. However, `import subprocess` fails with this error message, where the dynamic library doesn't find symbols from the Python code. The same code works when using `cargo run` instead of evcxr.
```text
Traceback (most recent call last):
  File "/usr/lib64/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/subprocess.py", line 74, in <module>
    import _posixsubprocess
ImportError: /usr/lib64/python3.10/lib-dynload/_posixsubprocess.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyTuple_Type
```

I use Python 3.10.0, rustc 1.56.0, PyO3 v0.15.0, and evcxr v0.12.0.

Since a dynamic library is involved, this might have something to do with the way evcxr compiles and executes the code. `@davidhewitt` from the PyO3 project offered help with the PyO3 specifics.

**Comment by bjorn3** [comment]
Can you try creating a library using pyo3 with the code that failed in evcxr and then add

```toml
[lib]
crate-type = ["dylib"]
```

to it's Cargo.toml and then create an executable that depends on this library with the main function calling the function of the library.

Another thing you can try if this doesn't error is to use the libloading crate to load the library from the executable instead of adding it as dependency.

**Comment by jonasbb** [comment]
Hi @bjorn3, thanks for the tip how to test dynamic linking and loading. It seems to be a problem with what libloading does, because simply using a dylib is not a problem. I have my test code in this repository: https://github.com/jonasbb/evcxr-issue-201
The `lib` has two functions, `import_sys` which does not exhibit any problems, and `import_subprocess` which does. `lib` has the dylib crate type like you suggested.

`prog` is a normal Rust program which uses `lib` as a dependency. It calls both functions and print
```text
import sys works!
import subprocess works!
```
indicating that there is no issue.

`loading` is a small program using libloading. It is quite simple and follows the documentation of libloading.
```rust
        let lib = libloading::Library::new("../target/debug/liblib.so").unwrap();
        let import_sys: libloading::Symbol<unsafe extern fn() -> ()> = lib.get(b"import_sys").unwrap();
        import_sys();
        let import_subprocess: libloading::Symbol<unsafe extern fn() -> ()> = lib.get(b"import_subprocess").unwrap();
        import_subprocess();
```
When run it works on the first function, but fails for subprocess with the familiar error.
```text
import sys works!
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ImportError'>, value: ImportError('/usr/lib64/python3.10/lib-dynload/_posixsubprocess.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyTuple_Type'), traceback: Some(<traceback object at 0x7f37e3f6c340>) }', lib/src/lib.rs:16:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bjorn3** [comment]
> This line could be the problem. If I understand it correctly, it prohibits other libraries (like _posixsubprocess.cpython-310-x86_64-linux-gnu.so) from observing any of the symbols in the dynamic library, including the important python symbols.

Yeah, that could be the issue. I believe CPython extensions depend on all CPython functions being in the global lookup scope rather than declaring a proper dependency on the CPython dylib. As workaround I think you can open the cpython dylib yourself without RTLD_LOCAL before initializing it.

**Comment by jonasbb** [comment]
```rust
let lib = unsafe {
    libloading::os::unix::Library::open(Some("/usr/lib64/libpython3.10.so"), libloading::os::unix::RTLD_NOW | libloading::os::unix::RTLD_GLOBAL)?
};
```
This works for now to make pyo3 work. It loads the Python dynamic library and exports all symbols for future use. It's not great. The path needs to be kept in sync with the installed Python version manually, and it uses the platform-specific API of libloading.

I don't know if there is something evcxr could be doing besides defaulting to `RTLD_GLOBAL`, which might or might not have other sideeffects.

**Comment by bjorn3** [comment]
Defaulting to `RTLD_GLOBAL` is likely a bad idea as two notebook cells may compile to two dylibs defining the same symbol with conflicting definitions, thus potentially causing the wrong definition to be used for the cell.

**Comment by jonasbb** [comment]
Since there is nothing easy which either evcxr or pyo3 can do, I just close this issue. Thanks for the help. Manually loading `libpython` with `RTLD_GLOBAL` is the workaround.
