### ISSUE TITLE
Type closure cannot currently be persisted

### ISSUE THREAD

**Issue by Jjjpan** [google/evcxr#205]
When I tried to run the cell bellow, an error occurs from rust_kernel.
```
let a = |x| x + 1;
a();
```
> Sorry, the type [closure@src/lib.rs:117:9: 117:18] cannot currently be persisted.

**Comment by davidlattimore** [comment]
I guess you saw that it isn't supported. You can sort of make it work if you can give the variable a named type, which you can do if you box the closure. e.g.

```rust
let a: Box::<dyn Fn(u32) -> u32> = Box::new(|x| x + 1);
(a)(41)
```
