### ISSUE TITLE
Rust REPL --opt argument not honored

### ISSUE THREAD

**Issue by nightrise** [google/evcxr#207]
Issue occurs in the latest version of the cargo crate (0.12.0 as of this writing): https://crates.io/crates/evcxr_repl
When running the repl via command-line and passing in the `--opt <level>` argument, the level is consistently ignored and simply set to a level of `2`. If no level is passed, it is set to `0`

Example Usage **with** --opt argument

```
evcxr --ide-mode --disable-readline --opt 0
Welcome to evcxr. For help, type :help
>> :opt
Optimization: 2
```

Example Usage **without** --opt argument
```
evcxr --ide-mode --disable-readline
Welcome to evcxr. For help, type :help
>> :opt
Optimization: 0
```

This is particularly egregious as the latest versions for IntelliJ IDE (2021.3) and its Rust Plugin (0.4.162.4321-213) contain an option to open a Rust REPL (dependent on evcxr). As part of invoking it, the `--opt 0` argument is passed in, which means the Optimization is set to `2` (when it should be 0). 

This contributes a noticeable slow-down to responsiveness, and there's no obvious way to make the Rust Plugin _omit_ the `--opt` argument.

**Comment by nightrise** [comment]
Nevermind -- misunderstood the usage of the `:opt` command. It isn't a getter, it is always a setter.

**Comment by thomcc** [comment]
Ha, this nerd sniped me last night and I spent around 20 minutes trying to figure out how we could be doing this wrong (it all *looked* fine). Glad to hear it's actually doing the right thing.

Perhaps we shouldn't accept `:opt` without an argument, though.

**Comment by nightrise** [comment]
Haha sorry about that! And yeah I think it is more of an issue of intuitive usage than of functionality.

Somewhat recently the default optimization level was also changed from 2 to 0 when unspecified in the command arguments -- but the `:opt` command is still setting the value to "2" when a blank value is passed in. 

I'd say the `:opt` command should either error out when a blank string is passed in, or make it clear that nothing has changed, and simply print out the current value.
