### ISSUE TITLE
Question: how to pronounce evcxr?

### ISSUE THREAD

**Issue by Jasper-Bekkers** [google/evcxr#215]
Honestly, I've been struggling, and now I'm curious ;-)

**Comment by davidlattimore** [comment]
I pronounce it eee-vic-ser. The name perhaps wasn't an ideal choice. I wanted something that was unique enough that you could do a Google search for things related to it - but pronunciation definitely isn't a strength of the name.

**Comment by Jasper-Bekkers** [comment]
Thanks!
