### ISSUE TITLE
Anonymous functions are not working in Jupyter Notebook: Sorry, the type [closure@src/lib.rs:192:9: 192:46] cannot currently be persisted

### ISSUE THREAD

**Issue by Austin-Routt** [google/evcxr#217]
Hi,

I'm new to Rust and evcxr, so I've been playing with various code snippets to grasp the language concepts. The concept I'm on now is "closures," but they do not seem to work in my jupyter notebook. For example, the following snippets of code result in a strange error:

```rust
let a = |x: i32, y| if x > y { x } else { y };
assert_eq!(a(1, 2), 2);
```
The error message is "Sorry, the type [closure@src/lib.rs:192:9: 192:46] cannot currently be persisted"
```rust
let a = 1;
let f = |x| x + a;
assert_eq!(f(2), 3);
```
Here the message is slighly different: "Sorry, the type [closure@src/lib.rs:193:9: 193:18] cannot currently be persisted"

I'm using anaconda on windows 10.

Does anyone know why this is happening?

**Comment by Austin-Routt** [comment]
Update: Anonymous functions work if they enclosed in another function.

For example, the following works:
```rust
fn main(){
let a = |x: i32, y| if x > y { x } else { y };
println!("{}",a(1, 2));
}

main();
``` 
Why can't anonymous functions standalone?

**Comment by davidlattimore** [comment]
Unfortunately it's a limitation of the way Evcxr works that it cannot persist variables with types that cannot be named. If you can give a type to your variable, then you can persist it. To give a name to a type like a closure, you'll probably need to box it. For example:

```rust
let a: Box<dyn Fn(u32) -> u32> = Box::new(|x| x + 1);
```

**Comment by Austin-Routt** [comment]
Yes, thank you @davidlattimore, Your example works perfectly. Have a great day.

**Comment by davidlattimore** [comment]
If you don't need to persist the variable containing the closure, then instead of wrapping everything in a function, you can wrap everything in braces. For example:

```rust
{
  let a = |x: i32, y| if x > y { x } else { y };
  println!("{}",a(1, 2));
}
```

This will make the variable `a` go out of scope, so evcxr won't try to persist the variable
