### ISSUE TITLE
[feature request] version that depends on zeromq rust library

### ISSUE THREAD

**Issue by derekdreery** [google/evcxr#223]
I'm having some terrible trouble using evcxr on my uni server, because they have a very convoluted setup. I can build all the rust stuff, but linking with the C deps doesn't work. I've had a look and it should be possible in theory to use the `zeromq` rust lib (native rust impl of zmq in the same github org as zmq itself), but would require moving to tokio from the thread-based approach used currently.

I'm not expecting anyone to actually implement this as it would be a lot of work, but I'm just registering an interest in case it ever happens.

**Comment by davidlattimore** [comment]
Hi @derekdreery. Sorry about the lack of an earlier reply. Thanks for pointing that out! That option didn't exist when I originally wrote the jupyter kernel. Not sure it'll happen soon, but I agree that it would be nice to have everything use native Rust.

**Comment by derekdreery** [comment]
Awesome, thanks!
