### ISSUE TITLE
Different use case for evcxr

### ISSUE THREAD

**Issue by yujong-lee** [google/evcxr#225]
I am comming from this:
https://github.com/google/evcxr/blob/6ae01aac84f6733c2ba3731a975486415500723a/evcxr/README.md?plain=1#L22-L25

Recently I wrote [`swc-plugin-eval`](https://github.com/yujong-lee/swc-plugin-eval/blob/main/src/lib.rs) for fun. I embed `js engine` to evaluate js expression at compile time.

Now, I am thinking of using `evcxr` to evaluate `rust code` rather than `js code`. Is there anything I have to know before getting started?

Thank you.

**Comment by davidlattimore** [comment]
Hi @yujong-lee - sorry about not replying sooner. I added an [example](https://github.com/google/evcxr/blob/main/evcxr/examples/example_eval.rs) of evaluating some Rust code using evcxr. Hopefully that helps.

**Comment by yujong-lee** [comment]
@davidlattimore  Thank you.
