### ISSUE TITLE
Allow `:dep`s to be interleaved with line comments

### ISSUE THREAD

**Issue by JohnScience** [google/evcxr#233]
Quite commonly I have something like this at the top of my cells:

```rust
:dep nalgebra = "0.31.0"
:dep nalgebra_latex = { version = "0.1.16", features = ["lin_sys", "evcxr"] }
//:dep nalgebra_latex = { path = "C:\\Users\\demen\\Documents\\GitHub\\nalgebra_latex", features = ["lin_sys", "evcxr"] }
```

Unfortunately, I'm forced to swap lines wherever I comment out one of them.

I use `shift + end` or `shift + home` to select whole lines but it's still tedious.

**Comment by davidlattimore** [comment]
Thanks, that sounds like a good suggestion.

If you (or anyone else) would like to have a try of implementing it, the code that looks for `:dep` lines is [here](https://github.com/google/evcxr/blob/c4b835dcd7b480b69ba6e3bb26f4ddbe1525215f/evcxr/src/code_block.rs#L207). It looks like an extra if-statement could be added there to check for comments.

**Comment by JohnScience** [comment]
@davidlattimore #234

**Comment by JohnScience** [comment]
Closed due to successful implementation and merging
