### ISSUE TITLE
Caret key (`^`) does not work as expected in evcxr_repl in vi edit mode

### ISSUE THREAD

**Issue by TonalidadeHidrica** [google/evcxr#239]
Caret key should jump the cursor to the first non-empty character in the current line.  But it is implemented that it instead jumps ...

```
❯ evcxr --edit-mode=vi
Welcome to evcxr. For help, type :help
>> abc def
       ^ here.
```

Seems that it instead moves the cursor to the character right after the first whitespace instead.

**Comment by davidlattimore** [comment]
Thanks for the report @TonalidadeHidrica. Evcxr uses [rustyline](https://github.com/kkawakam/rustyline). Looks like it exhibits the same behaviour. Would you like to raise an issue there?

**Comment by davidlattimore** [comment]
The relevant code, in case you wanted to have a look at changing it, appears to be [here](https://github.com/kkawakam/rustyline/blob/746e43a1c31a6c943c12e7b8a8bd5afe60f87ab5/src/command.rs#L52).

**Comment by TonalidadeHidrica** [comment]
Thank you very much for investigating!  I will open an issue in rustyline.
