### ISSUE TITLE
Unable to use environment variable for compilation

### ISSUE THREAD

**Issue by tomkimsour** [google/evcxr#259]
I am trying to make tch-rs work in jupyter notebook, I am able to run std libraries however running code depending of tch-rs wouldn't work.

```rust
:dep tch = "0.10.1"

use tch::Tensor;
let mut t: Tensor = Tensor::randn(&[2,3,4], tch::kind::FLOAT_CPU); 
```

The documentation says you need to ```export LIBTORCH=/path/to/libtorch and export LD_LIBRARY_PATH=${LIBTORCH}/lib:$LD_LIBRARY_PATH``` before running cargo run which I did before trying jupyter notebook and it works. I also added them to my .zshrc

So my question is how do I make it so the environment loads these two environment variables ? Is it even possible ?

**Comment by tomkimsour** [comment]
It seems it would work if i export the variable and then call ```jupyter notebook``` and edit my code in the web browser. However it still wouldn't work using the vscode extension

**Comment by davidlattimore** [comment]
Does LD_LIBRARY_PATH need to be set when you `cargo build`, when the run the resulting binary, or both? My guess would be either runtime only, or both. Put another way, does `cargo build` succeed if you don't set LD_LIBRARY_PATH?

You should be able get it to work in the vscode extension by setting the environment variable in a shell, then launching vscode from that shell

**Comment by tomkimsour** [comment]
starting vscode from a shell does work. Thanks for this workaround
