### ISSUE TITLE
Incremental computing: Adapton?

### ISSUE THREAD

**Issue by davidblewett** [google/evcxr#28]
I'm curious if you have seen the [Adapton](https://github.com/adapton/adapton.rust) project? It could be a way to help optimize a notebook.

Apologies if this isn't the right way to provide suggestions; I didn't see a mailing list or other community information.

**Comment by davidlattimore** [comment]
Raising issues if fine for now. I've been meaning to create a mailing list or two, but haven't gotten to it yet.

Thanks for the suggestion. I hadn't seen Adapton. It looks interesting. I'm unsure though how it would be of use to Evcxr. Are you able to explain more what you had in mind?

**Comment by davidblewett** [comment]
I have not dug into how execution works, but in the context of a notebook this example seems relevant: https://docs.rs/adapton/0.3.30/adapton/#demand-driven-change-propagation . It allows for only recomputing statements when a change is made, and the result is actually requested.

**Comment by davidlattimore** [comment]
I'm just going through seeing with old issues I can close. I agree that demand driver change propagation is a good way for a compiler to operate. Unfortunately in the case of evcxr, we don't really have control over that. We just call out to rustc via cargo. If at some point enough of the compiler was broken out into separate crates, we could look at using those crates directly. At that point and with sufficient incremental compilation in the compiler, it might start to look a little like you describe. So I hope eventually evcxr, or an alternative REPL for rust operates something like you describe. For now though, I'll close this issue, as I can't see any progress in that direction in the short to medium term. Thanks for the suggestion though and sorry for being about 2 years late replying to your last message
