### ISSUE TITLE
Add tab completion

### ISSUE THREAD

**Issue by davidlattimore** [google/evcxr#3]
Probably by integrating with RLS, although I'm open to other ideas if anyone has any.

**Comment by davidlattimore** [comment]
I've added tab completion to the jupyter kernel (using rust-analyzer). The REPL still has history-based tab completion. @aminroosta or anyone else, do you have any opinion on the best way forward with the REPL? Should we switch it to just use rust-analyzer based completion, or is there value in the keeping the history-based completion? If we were to have both, do you think a config option to switch between them, or get results from both and merge them somehow?

**Comment by aminroosta** [comment]
First, thanks for adding the rust-analyzer to jupyter kernel :+1: - I will definitely check that out.
  
As for the REPL, considering rust-analyzer completions are way smarter, i personally see little point in keeping history-based completion.  

My guess is that most of those variable or function names, will also be suggested by rust-analyzer.

**Comment by davidlattimore** [comment]
Cool. I've just pushed a change to integrate it into the REPL. I'll probably do a release soon, but if anyone notices any problems with what's at HEAD, please do let me know.

I included function arguments in the tab completion. So the completion might look like `slice_unchecked(begin, end)`. Not sure if having the `(begin, end)` there is good or not. Open to feedback. We can make it a config option if there's differing preferences.
