### ISSUE TITLE
Add multiline support in the REPL

### ISSUE THREAD

**Issue by davidlattimore** [google/evcxr#4]
Can possibly use syn to parse what's been written and keep asking for more lines of input until syn reports that there's a complete token tree.

Alternatively, perhaps we can use a key modifier - e.g. shift+enter to execute. Perhaps need to first see what other REPLs do. Jupyter notebook uses shift+enter to execute, but then it's not a command line REPL (although jupyter-console is)

**Comment by mockersf** [comment]
Scala and Python REPL both are waiting for a complete token tree.

Scala REPL also has a mode triggered with `:paste` that will not trigger evaluation until `ctrl-D` is sent
