### ISSUE TITLE
Failed to build 

### ISSUE THREAD

**Issue by VentGrey** [google/evcxr#49]
```
error: failed to run custom build command for `zmq-sys v0.8.3`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installo751eq/release/build/zmq-sys-38aba20ccedde92d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to locate libzmq:
Failed to run `"pkg-config" "--libs" "--cflags" "libzmq >= 3.2"`: No such file or directory (os error 2)', /home/omar/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-sys-0.8.3/build.rs:31:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `evcxr_jupyter v0.3.4`, intermediate artifacts can be found at `/tmp/cargo-installo751eq`
```

However 

```
libzmq3-dev it's already installed (4.3.1-4).
```

Any thoughts on this?

**Comment by davidlattimore** [comment]
Guessing you've solved this yourself. If not, perhaps try running the pkg-config command that it says is failing. Perhaps you need to install pkg-config.

**Comment by VentGrey** [comment]
pkg-config was installed. I used the magic formula of uninstalling and reinstalling.

**Comment by PrathivKrishnaR** [comment]
> pkg-config was installed. I used the magic formula of uninstalling and reinstalling, sorry for the inconvenience.

dude am getting the same error while trying to cargo build libindy for indy-sdk, how do i solve this

**Comment by davidlattimore** [comment]
Evcxr no long uses zmq-sys, since it now uses a native Rust implementation of zmq. Not sure what you're trying to compile @PrathivKrishnaR, but perhaps try asking on their forums?
