### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by axil** [google/evcxr#53]
```
  = note: libzmq-50f4a406b22aace0.rlib(zmq-50f4a406b22aace0.zmq.adwk1sko-cg
u.4.rcgu.o) : error LNK2019: unresolved external symbol __imp_zmq_msg_gets
referenced in function _ZN3zmq7message7Message4gets17h7fa806d7747a2351E
          libzmq-50f4a406b22aace0.rlib(zmq-50f4a406b22aace0.zmq.adwk1sko-cg
u.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_zmq_proxy_ste
erable referenced in function _ZN3zmq15proxy_steerable17h28199adb82db8604E
          libzmq-50f4a406b22aace0.rlib(zmq-50f4a406b22aace0.zmq.adwk1sko-cg
u.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_zmq_has refer
enced in function _ZN3zmq3has17h8a1799c5696eeb89E
          C:\Documents\rust\evcxr\target\debug\deps\evcxr_jupyter-04a8e2112
da4bb74.exe : fatal error LNK1120: 3 unresolved externals

```
I'm on Windows 10, first tried to `cargo install evcxr-jupyter`, got an error described [here](https://github.com/erickt/rust-zmq/pull/241#issuecomment-472105164), then cloned the master branch and trying to build it. 
I've installed ZeroMQ 4.0.4 via installer, renamed lib and dll files as recommended and added .dll dir to PATH.

**Comment by axil** [comment]
The solution is to compile zeromq 4.3.2 manually (cmake+visual studio).

**Comment by hajsf** [comment]
> The solution is to compile zeromq 4.3.2 manually (cmake+visual studio).

How, any guidelines?

**Comment by axil** [comment]
@hajsf The binaries from the zeromq official site are supposed to be linked dynamically, but evcxr is designed to link in statically, so manual build is necessary.

1. Download cmake from https://cmake.org/download/
2. Download libzmq v4.3.2 source from https://github.com/zeromq/libzmq/releases
3. Run cmake-gui
4. Choose source and destination directories
5. Press 'configure', choose your visual studio _and_ platform (x64 is not the default!)
6. Press 'generate'
7. Press 'open project' _or_ open the generated solution in visual studio manually
8. Build the "Release" configuration
9. Copy \lib\Release\libzmq-v140-mt-4_3_2.lib to Program Files\ZeroMQ 4.0.4\lib\zmq.lib
(I had zeromq404 installed already, if you don't you might want to manually set LIBZMQ_PREFIX to an arbitrary location - it doesn't need anything from there except the `lib` dir and `zmq.lib` file there)
10. `cargo install evcxr_jupyter`

It might be a good idea to `cargo install sccache` first to cache the results of `cargo install` from the last step (in case something goes wrong and you have to run it several times).

**Comment by axil** [comment]
You might also want to have a look at my [rust-magic](https://github.com/axil/rust-magic) project, which is an alternative to evcxr-jupyter for small notebooks: it doesn't keep state between running cells, but has shorter run times (usually within 1 second on an average machine). The user interface is under active development and not frozen so far, so I'm not willing to show it to wide public yet

**Comment by hajsf** [comment]
> rust-magic

Thanks a lot, this is really much smoother for my needs, I liked the way of using `jupyter lab` in running short codes either for quick testing or educational purposes, [rust playground](https://play.rust-lang.org/) is call, but with poor internet it is useless.
rust_magic worked perfectly for me at both Mac and Win10. thanks for sharing it.

**Comment by hajsf** [comment]
> 8\. Build the "Release" configuration

I got this error:

![image](https://user-images.githubusercontent.com/46838626/64425103-8d4f0400-d0b3-11e9-874f-72ae464abfdc.png)

**Comment by davidB** [comment]
OT
@hajsf  for demo or tutorial (w/o internet) I used cargo-script + vscode with 2 panes (editor & output) (more details at https://github.com/davidB/hello_rs_overdesign/blob/master/README.md).

**Comment by hajsf** [comment]
Thanks @davidB  either I did not understand how to use it, or it is not matching my needs, for simple `println!()` statement I got below error:

![image](https://user-images.githubusercontent.com/46838626/64428843-6bf31580-d0bd-11e9-90d6-9d2a10aeb96c.png)

**Comment by axil** [comment]
@davidB actually, rust_magic is just a thin wrapper around `cargo script` with some benefits of:
 - seeing results of previous cell runs in the notebook
 - no need to write 'fn main()' every time I copy-paste an example from the net
 - having python cells to quickly calculate or plot something
 - ability to test a cell during/right after it was written, then change its status to 'rust_func' so that it prepended to the subsequent calls
etc
But it is not meant as a substitution of evcxr because it does not store the state of the variables between the cell runs.

**Comment by axil** [comment]
@hajsf Looks like you're _running_ a _Debug_ configuration. You need to (a) switch from Debug to Release in the dropdown menu and (b) build (ctrl-shift-b) instead of running (ctrl-f5) the project.

**Comment by hajsf** [comment]
> build (ctrl-shift-b)

Well, I did, and downloaded [zeromq-4.0.4.zip](http://download.zeromq.org/) unzipped it, created a folder called `lib` inside it, and copied inside this `lib` folder the generated files in `\zeromq-4.3.2\lib\Release` from the previous step.

Also I created a `PATH` to the `C:\Program Files\zeromq-4.0.4`

So my files are as shown below:

![image](https://user-images.githubusercontent.com/46838626/64450562-12094480-d0eb-11e9-9e03-de1d2eb1c593.png)

Then I run `cargo install evcxr_jupyter` and got the below error:
```bash
   Compiling generic-array v0.12.3
error: failed to run custom build command for `zmq-sys v0.9.1`

Caused by:
  process didn't exit successfully: `C:\Users\HASAN~1.DES\AppData\Local\Temp\cargo-installtLPBBw\release\build\zmq-sys-fbb2a707b4efd65a\build-script-main` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to locate libzmq:
Failed to run `"pkg-config" "--libs" "--cflags" "libzmq" "libzmq >= 4.1"`: The system cannot find the file specified. (os error 2)', C:\Users\hasan.DESKTOP-HU2FQ29\.cargo\registry\src\github.com-1ecc6299db9ec823\zmq-sys-0.9.1\build\pkg_config.rs:25:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `evcxr_jupyter v0.4.4`, intermediate artifacts can be found at `C:\Users\HASAN~1.DES\AppData\Local\Temp\cargo-installtLPBBw`

Caused by:
  build failed
```

**Comment by axil** [comment]
@hajsf It's not PATH, it's LIBZMQ_PREFIX
Also you need to rename libzmq-v140-mt-4_3_2.lib to zmq.lib

**Comment by hajsf** [comment]
> it's LIBZMQ_PREFIX

Did not understand this?

**Comment by axil** [comment]
@hajsf LIBZMQ_PREFIX should point to "C:\Program Files\zeromq-4.0.4" (without the trailing "lib").

**Comment by hajsf** [comment]
@axil same issue :(

![image](https://user-images.githubusercontent.com/46838626/64485056-f35a9900-d223-11e9-8958-54cb41bbb4c0.png)

**Comment by axil** [comment]
@hajsf Try copying the zmq.lib file directly to 
C:\Users\<your_username>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib

**Comment by hajsf** [comment]
> Try copying the zmq.lib file directly to

Wow, finally completed

![image](https://user-images.githubusercontent.com/46838626/64551742-75d77b80-d33e-11e9-90c8-c071d18cd1ff.png)

Now the other big question, how to start, I do not see anything in `Jupyter`:

![image](https://user-images.githubusercontent.com/46838626/64551724-61937e80-d33e-11e9-8717-c60c7e2a9846.png)

**Comment by axil** [comment]
@hajsf Good news! :) 

Try `evcxr_jupyter --install`

**Comment by davidlattimore** [comment]
From the screenshot, it looks like --install was already run. Perhaps the location it's installing into is not one of the locations where Jupyter is checking. Hmm, actually, I thought --install was supposed to print out all the filenames it wrote to, but I don't see any such output in the screenshot.

**Comment by axil** [comment]
- Copy `libzmq-v142-mt-4_3_2.dll` from `\bin\Release` to `C:\Program Files\ZeroMQ 4.0.4\bin` and make sure that this directory is in the PATH _or_
- Copy it to `c:\windows\system32`

**Comment by hajsf** [comment]
I did both, but nothing changed

![image](https://user-images.githubusercontent.com/46838626/64600717-4cf9c980-d3c4-11e9-9186-15f896bc85e1.png)

**Comment by hajsf** [comment]
> I thought --install was supposed to print out all the filenames it wrote to

In Mac it did
```bash
Hasans-Air:~ hasan$ evcxr_jupyter --install
Writing /Users/hasan/Library/Jupyter/kernels/rust/kernel.json
Writing /Users/hasan/Library/Jupyter/kernels/rust/logo-32x32.png
Writing /Users/hasan/Library/Jupyter/kernels/rust/logo-64x64.png
Writing /Users/hasan/Library/Jupyter/kernels/rust/logo-LICENSE.md
Installation complete
```

**Comment by hajsf** [comment]
Trying to install `ijavascript` and it did not detect the `zeromq` and trying to get it downloaded and installed, but it take ages :(

![image](https://user-images.githubusercontent.com/46838626/64624032-b09aeb80-d3f2-11e9-956f-00686c7f1191.png)

**Comment by axil** [comment]
@hajsf In my last post I told you to copy the *dll* file:

>  Copy libzmq-v142-mt-4_3_2.dll from \bin\Release

but you copied the *lib* file from the \lib\Release directory. Please copy the dll file.

**Comment by hajsf** [comment]
mm, I remove nodejs and python2.7, and did the below:
1. installed nvm from [here](https://github.com/coreybutler/nvm-windows)
2. installed node 8, as: `nvm install 8.0`
3. used this node version as `nvm use 8.0.0`
4. installed ijavascript as: `npm install -g ijavascript`
5. run ijavascript as `ijsinstall`
It is running now, and I got `C:\Program Files\nodejs\node_modules\ijavascript\node_modules\zeromq` created that contains the below, not sure if we can use any of them!!:

![image](https://user-images.githubusercontent.com/46838626/64629464-eb555180-d3fb-11e9-8c96-8b425510b5cf.png)

![image](https://user-images.githubusercontent.com/46838626/64629511-0031e500-d3fc-11e9-9244-aa93239c0b8c.png)

![image](https://user-images.githubusercontent.com/46838626/64629543-0c1da700-d3fc-11e9-8da2-03a100077989.png)

![image](https://user-images.githubusercontent.com/46838626/64629557-163fa580-d3fc-11e9-8f46-ba17edfddc01.png)

![image](https://user-images.githubusercontent.com/46838626/64629587-248dc180-d3fc-11e9-8fed-73a58b9cc622.png)

![image](https://user-images.githubusercontent.com/46838626/64629612-31121a00-d3fc-11e9-839b-942d416beb62.png)

![image](https://user-images.githubusercontent.com/46838626/64629681-54d56000-d3fc-11e9-8b53-0a984774d4f4.png)

**Comment by hajsf** [comment]
> In my last post I told you to copy the _dll_ file

mm, I'll try it now and come back to you.

**Comment by hajsf** [comment]
wooow, finally done :)
I think you need now to re-write the installation procedures for windows or guide for this thread :)

![image](https://user-images.githubusercontent.com/46838626/64630717-5a33aa00-d3fe-11e9-9672-89bdc35b1554.png)

![image](https://user-images.githubusercontent.com/46838626/64630733-628be500-d3fe-11e9-8540-a05542ca2d4c.png)

**Comment by axil** [comment]
So the revised algorithm to install `evcxr_jupyter` on windows looks like this:

1. Download cmake from https://cmake.org/download/
2. Download libzmq v4.3.2 source from https://github.com/zeromq/libzmq/releases
3. Run cmake-gui
4. Choose source and destination directories
5. Press 'configure', choose your visual studio version and platform (x64 is not the default!)
6. Press 'generate'
7. Press 'open project' or open the generated solution in visual studio manually
8. Build the "Release" configuration
9. Copy \lib\Release\libzmq-v140-mt-4_3_2.lib to C:\Program Files\ZeroMQ\lib\zmq.lib
and \bin\Release\libzmq-v142-mt-4_3_2.dll to C:\Program Files\ZeroMQ\bin\libzmq-v142-mt-4_3_2.dll
10. Create environment variable LIBZMQ_PREFIX and set it to `C:\Program Files\ZeroMQ`
11. Add `C:\Program Files\ZeroMQ\bin` to PATH.
11. `cargo install evcxr_jupyter`
12. `evcxr_jupyter --install`
13. `jupyter-notebook`
14. `New` button - you should have "Rust" in the list of available kernels.

NB 11-th step takes quite a while to complete. Installing sccache (`cargo install sccache`) before evcxr_jupyter reduces this time through caching the dependencies compilation results.

@hajsf Please check if I put it right.

**Comment by hajsf** [comment]
@axil  I'd like to suggest the below tuning:
Point 8, add: make sure to select build (ctrl-shift-b)
Point 9 could be better if split into 2 point, one for the `lib` file in `lib` folder, and one for `dll` file in `bin` folder
NB11 about `cargo install sccache` could be better as a separate point after point 11, I myself missed it the first time :)
After point 13 better to make this statement to confirm installation, 
`you should see the locations where the file saved, like:
Writing C:\\Users\...\Jupyter\kernels\rust\kernel.json
Writing C:\\Users\...\Jupyter\kernels\rust\logo-32x32.png
Writing C:\\Users\...\Jupyter\kernels\rust\logo-64x64.png
Writing C:\\Users\...\Jupyter\kernels\rust\logo-LICENSE.md
```
Also adding checking installed kernels in the command line before running Jupyter could be fine, like:
```bash
C:\WINDOWS\system32>jupyter kernelspec list
Available kernels:
  rust          C:\Users\hasan.DESKTOP-HU2FQ29\AppData\Roaming\jupyter\kernels\rust
  python       c:\program files\python37\share\jupyter\kernels\python
--and other if available
```

**Comment by axil** [comment]
@hajsf Updated. As for quoting the `evcxr_jupyter --install` output - the instruction is already too long; it'd be more rational for the package author to make its output more verbose in case of an error (@davidlattimore would you have a look?).

**Comment by davidlattimore** [comment]
Better error reporting definitely sounds like a good idea to me. I just tried running evcxr_jupyter --install in a way that caused it to error and it did print an error message. The error message didn't include the filename, so I should fix that. But I'm not sure why it would produce no output at all on error, which from what I could tell above was what was happening. Was the issue that the binary evcxr_jupyter was failing to start because it was missing a required DLL? If the binary isn't starting, then I'm not sure there's much I can do in terms of error reporting. There's perhaps something I'm not understanding though.

Thanks both of you for persevering with this. It's great to have some concrete instructions for Windows, even if they are longer than we'd like.

**Comment by axil** [comment]
In my case it did show a warning message about the missing dll:
![image](https://user-images.githubusercontent.com/170910/64668195-e25d9200-d486-11e9-9ee9-58d389f0063f.png)

I'd suggest to leave it as is for now.

If in future there're other reports that the message doesn't show up maybe it makes sense to write a python script instead that performs the copying and doesn't depend on any dlls. It could also check if this dll exists in PATH and show a warning message if it doesn't.

**Comment by hajsf** [comment]
Do you like to send you the 2 files generated with me, `.lib` and `.dll` if you like to upload and share them with the repo?

**Comment by axil** [comment]
@hajsf I don't think it is a good idea. As far as I understand, they will only work on a limited number of computers - it might depend on processor version, windows version, visual c++ runtime version and what not. The algorithm above is good enough to work on any modern PC.

**Comment by hajsf** [comment]
Thanks @axil for the explanation.

**Comment by hasanOryx** [comment]
I noticed you made it easier [here](https://github.com/google/evcxr/tree/master/evcxr_jupyter#windows) just did it in office laptop and things going smoothly. thanks

**Comment by davidlattimore** [comment]
Good to hear. Thanks for the feedback :)
