### ISSUE TITLE
Something is wrong with the globals

### ISSUE THREAD

**Issue by axil** [google/evcxr#55]
I'm new to Rust, but it looks as if something is not right with the globals:
![image](https://user-images.githubusercontent.com/170910/63381411-d0765b00-c3c2-11e9-804b-c55263b78dc4.png)
I understand that globals do not exist in rust per se, but mut statics behave the same way:
![image](https://user-images.githubusercontent.com/170910/63381442-e4ba5800-c3c2-11e9-9224-af9a041155cb.png)

**Comment by davidlattimore** [comment]
Arg, that's embarrassing. I thought I had a test for that. Mostly likely a regression in 0.4.0. Thanks heaps for reporting that. Will try to fix it soon and push a new release.

**Comment by davidlattimore** [comment]
Damn. I did have a test for it, the test picked up the problem, I misinterpreted why the test had failed and changed the test to enable the old behavior. As a temporary workaround you can do `:preserve_copy_types` to reenable the old behavior (this is basically what I made the test do).
