### ISSUE TITLE
I keep getting libctx error every expression

### ISSUE THREAD

**Issue by GrayJack** [google/evcxr#69]
When I start evcxr i get this error
`Error renaming '"/tmp/.tmpv1xw2x/target/debug/deps/libctx.so"' to '"/tmp/.tmpv1xw2x/target/debug/deps/libcode_1.so"': No such file or directory (os error 2)`

But it also happens after every expression put in the repl

**Comment by davidlattimore** [comment]
Hi @GrayJack . Thanks for the report. To help figure out what's happening, would you be able to do the following?

- From evcxr, after entering an expression, type `:last_compile_dir`
- In a separate terminal, cd to the directory that it printed.
- Check to see if target/debug/deps/libctx.so exists.
- What about target/debug/libctx.so ?
- Run `cargo rustc --message-format=json -- -C prefer-dynamic`
- After that, which of those files exists?

Also possibly useful:

- Output of rustc --version
- What OS / distribution are you running?

On my system both files are created (target/debug/deps/libctx.so and target/debug/libctx.so). Actually, they're the same file, but one is hard linked to the other. I'm not sure why I chose to make use of the one in the "deps" directory. I note that cargo now emits some JSON that says what file was created (for me, it indicates the non-deps directory filename). Perhaps I should switch to reading that JSON.

**Comment by GrayJack** [comment]
Sorry, forgot about those infos
Rustc: rustc 1.40.0-nightly (1423bec54 2019-11-05)
OS: Linux, version 5.3.10

> From evcxr, after entering an expression, type `:last_compile_dir`
It gives me the same error
```sh
Error renaming '"/tmp/.tmpL77Dg7/target/debug/deps/libctx.so"' to '"/tmp/.tmpL77Dg7/target/debug/deps/libcode_3.so"': No such file or directory (os error 2)
```

> In a separate terminal, cd to the directory that it printed.
The max it can go is `/tmp/.tmp<random>/` with the following tree
```sh
.
├── Cargo.lock
├── Cargo.toml
└── src
    └── lib.rs
```

> Check to see if target/debug/deps/libctx.so exists.
>  What about target/debug/libctx.so

Because of the above, neither exist

Maybe it's related to me having a custom target folder for my rust environment?

> Run `cargo rustc --message-format=json -- -C prefer-dynamic`

Yeah, that proves it, it is because of my custom target folder
```
{"reason":"compiler-artifact","package_id":"ctx 1.0.0 (path+file:///tmp/.tmpL77Dg7)","target":{"kind":["cdylib"],"crate_types":["cdylib"],"name":"ctx","src_path":"/tmp/.tmpL77Dg7/src/lib.rs","edition":"2018","doctest":false},"profile":{"opt_level":"2","debuginfo":null,"debug_assertions":true,"overflow_checks":true,"test":false},"features":[],"filenames":["/home/grayjack/MySources/.cargo_target/debug/libctx.so"],"executable":null,"fresh":true}
```

**Comment by davidlattimore** [comment]
Ah, that makes sense. I assume you've set the target directory via the environment variable CARGO_TARGET_DIR? Or some other mechanism?

I'll make a change to ignore CARGO_TARGET_DIR.

**Comment by GrayJack** [comment]
Yeah, via environment variable
