### ISSUE TITLE
Using local dependencies

### ISSUE THREAD

**Issue by viniciusd** [google/evcxr#71]
We should add external dependencies with the :dep keyword.

However, how can one run a local crate? I tried starting jupyter notebook from my crate directory, yet it wasn't able to find my crate.

**Comment by davidB** [comment]
Use dep defines with path like in cargo.toml.

Le dim. 24 nov. 2019 à 20:34, Vinícius Dantas <notifications@github.com> a
écrit :

**Comment by viniciusd** [comment]
That works, thanks

**Comment by kootenpv** [comment]
It's not clear... given a TLD with a Cargo file like

```
[workspace]
members = ["coalmine"]
```

how can I use `:dep`?
