### ISSUE TITLE
Bad code generation after an integer overflow

### ISSUE THREAD

**Issue by orium** [google/evcxr#76]
Hi.

It seems this particular overflow causes the repl to always generate wrong code on subsequent expression:

```text
$ evcxr
Welcome to evcxr. For help, type :help
>> 10u8.pow(5)
thread '<unnamed>' panicked at 'attempt to multiply with overflow', /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/num/mod.rs:3686:24
stack backtrace:
⋮
Child process terminated with status: exit code: 101
>> 1
A compilation error was found in code we generated.
Ideally this should't happen. Type :last_error_json to see details.
error: linking with `cc` failed: exit code: 1
⋮
```

**Comment by davidlattimore** [comment]
Thanks for the report. I cut down the generated code to something minimal and filed https://github.com/rust-lang/rust/issues/67118

**Comment by davidlattimore** [comment]
The bug in rustc was fixed in late 2019. Just retried the original repro and indeed the problem no longer reproduces. I probably should have closed this sooner. Thanks again for reporting.
