### ISSUE TITLE
Allow customizing config dir

### ISSUE THREAD

**Issue by thomcc** [google/evcxr#78]
On macOS this uses `~/Library/Preferences/evcxr`. I'd prefer this to be in my home dir (ideally `~/.config/evcxr` like on other unixes), as this is consistent with other CLI tools and etc. (`~/Library/Preferences` is really mostly used for GUI applications...).

Allowing it to be overridden by a `EVCXR_CONFIG_DIR` environment variable would be nice and not break anybody, I could file a PR for this if you'd accept it.

**Comment by davidlattimore** [comment]
Evcxr just defers to the dirs crate - https://crates.io/crates/dirs - to determine where to read config files from. Perhaps it's ideas of where things should go on different platforms is out of step with those platforms? But, regardless, I'd be happy to accept a PR for adding an EVCXR_CONFIG_DIR.

**Comment by thomcc** [comment]
> Perhaps it's ideas of where things should go on different platforms is out of step with those platforms

Yeah, not sure. Generally things use `Library/Application Support` (which it calls `data_dir()`), but even then I generally don't expect things that aren't `.app` bundles to write into `~/Library` (or `/Library`). Either way, it's not like they can really change it without breaking anybody who uses it currently (same situation as with std::env::home_dir...).
