### ISSUE TITLE
Support loading a prelude file?

### ISSUE THREAD

**Issue by thomcc** [google/evcxr#79]
As I mentioned in https://github.com/google/evcxr/issues/67#issuecomment-562889010, it's a bit annoying to 

Currently one option would be for me to define this in a separate crate (say 'thom_evcxr_prelude'), use `:dep thom_evcxr_prelude { path = "/Users/thom/src/thom_evcxr_prelude }` followed by `use thom_evcxr_prelude::*`.

However, when I tried this it impacted startup time of evcxr noticeably, and so I chose to just put everything on one line, since I start evcxr much more often than I touch that file. Defining a separate crate also feels like overkill if you have just, say, a small number of declarations and use statements which might be too involved to conveniently fit on one line (the initial suggesion in https://github.com/google/evcxr/issues/67#issuecomment-553833421 for example)

An easy solution would be just to have `<evcxr config dir>/prelude.rs` which is loaded as a single rust expression after init.evcxr runs (doing it after allows init.evcxr to include a dep, which the prelude uses, for example).

Alternatively, a `:load <path/to/blah.rs>` might be a more general useful feature, and would allow splitting to multiple files, and solves the 'when should it run' question, but seems like it might confuse users who try to point it at a lib.rs or mod.rs or something, and have it cause problems that way.

I would be happy to submit a PR for this if it would be accepted.

**Comment by thomcc** [comment]
Ah, something like this is in TODO.md already, I'll put up a PR for it then since it seems easy.

**Comment by davidlattimore** [comment]
My initial reaction was that I didn't want to have two different on-startup mechanisms if init.evcxr could be fixed, but thinking about it some more, one advantage of having the rust code to be executed in a separate file is that it wouldn't include any evcxr commands, so could have a .rs extension and could be handled properly by an editor. So sure, I'd say I'd be happy to accept a PR for a separate file.

**Comment by thomcc** [comment]
>  the rust code to be executed in a separate file is that it wouldn't include any evcxr commands, so could have a .rs extension and could be handled properly by an editor

Yeah, that's more or less exactly why I want it.
