### ISSUE TITLE
Pickup config dir environment var

### ISSUE THREAD

**Issue by oefd** [google/evcxr#8]
As per [this](https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#envvar-JUPYTER_CONFIG_DIR) it seems like the install operation should choose to use `$JUPYTER_CONFIG_DIR/kernels` where possible for installing the kernel.

**Comment by davidlattimore** [comment]
Thanks for pointing that out. I also found [this](https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernelspecs) documentation indicating that I should perhaps use ~/.local/share/jupyter by default.
