### ISSUE TITLE
"type annotations needed" when I run the following code second time

### ISSUE THREAD

**Issue by suda-morris** [google/evcxr#83]
Here is the test code used to illustrating “Type Inference" in Rust:
```rust
let player_scores = [
    ("Jack", 20), ("Jane", 23), ("Jill", 18), ("John", 19),
];

let players : Vec<_> = player_scores
    .iter()
    .map(|&(player,_score)|{
            player
    })
    .collect();
println!("{:?}",players);
```
The first time run the code, result is just what I want:
```bash
["Jack", "Jane", "Jill", "John"]
```
But the second time run the cell, it gave me error:
```bash
type annotations needed
```
Restart kernel can help to resolve, but still can't run the code more than once.

**Comment by davidlattimore** [comment]
Thanks for the report. I think this should hopefully be relatively straightforward to fix.

In the meantime, if you'd like a workaround, it should work if you either fully specify the type of `players`, or don't specify it at all. e.g:

```rust
let players : Vec<&'static str> = player_scores
    .iter()
    .map(|&(player,_score)|{
            player
    })
    .collect();
```

or

```rust
let players = player_scores
    .iter()
    .map(|&(player,_score)|{
            player
    })
    .collect::<Vec<_>>();
```
