### ISSUE TITLE
failed to compile on macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by rambasnet** [google/evcxr#86]
I've anaconda and many Jupyter notebook kernels installed fine on my macOS. I get this error while install evcxr, any thoughts:
error: failed to run custom build command for `zmq-sys v0.11.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installmLenFM/release/build/zmq-sys-e7791843ff64e4f5/build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build/main.rs
cargo:rerun-if-env-changed=PROFILE
running: "cmake" "/Users/rbasnet/.cargo/registry/src/github.com-1ecc6299db9ec823/zeromq-src-0.1.8+4.3.2/vendor" "-DCMAKE_INSTALL_LIBDIR=lib" "-DCMAKE_C_STANDARD=99" "-DZMQ_BUILD_TESTS=OFF" "-DENABLE_DRAFTS=OFF" "-DCMAKE_BUILD_TYPE=Release" "-DWITH_PERF_TOOL=OFF" "-DBUILD_SHARED=OFF" "-DBUILD_STATIC=ON" "-DWITH_LIBSODIUM=OFF" "-DCMAKE_INSTALL_PREFIX=/tmp/cargo-installmLenFM/release/build/zmq-sys-52df88333c826791/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++"

--- stderr
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?

build script failed, must exit now', /Users/rbasnet/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.42/src/lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `evcxr_jupyter v0.4.7`, intermediate artifacts can be found at `/tmp/cargo-installmLenFM`

Thank you!

**Comment by rambasnet** [comment]
Never mind, as the error says I didn't have cmake commandline installed. This: https://stackoverflow.com/questions/30668601/installing-cmake-command-line-tools-on-a-mac helped me do that. Installed fine after that. Thank you!!

**Comment by davidlattimore** [comment]
Thanks for reporting that. I've added it to the installation instructions for Mac OS.
