### ISSUE TITLE
Not finding toolchain

### ISSUE THREAD

**Issue by vickumar1981** [google/evcxr#89]
I might have missed a step somewhere, but I've installed rust 1.40 via rustup, I have `$CARGO_HOME/bin` directory in my `PATH`, I've set the `CARGO_HOME` to the `.cargo` folder.

The rust compiler looks to be installed
```
> rustc --version
rustc 1.40.0 (73528e339 2019-12-16)
```

When I try to create a new rust notebook, the jupyter logs show:
```
Error: Message("Compilation failed, but no parsable errors were found. STDERR:\nerror: no default toolchain configured\n\nSTDOUT:\n")
```

I've also run the `rustup` up commands to try and set the toolchain:
```
rustup install stable
rustup default stable
```

Thanks.

**Comment by davidlattimore** [comment]
Thanks for the report. I haven't seen that before and don't know what the problem might be, but doing the following might give some clues:

From evcxr, evaluate `:last_compile_dir`. Then from a shell, change to that directory and run `cargo build`.

**Comment by davidlattimore** [comment]
Feel free to reopen if you can provide more details.
