### ISSUE TITLE
`format!` garbage data and segfault in repl

### ISSUE THREAD

**Issue by thomcc** [google/evcxr#93]
I'm on macOS 10.14.6, evcxr 0.4.7, rust 1.40.0

From a fresh repl:
```
>> format!("{:x}", 2)
"656d6f5300000002"
>> format!("{:2x}", 2)
Segmentation fault.
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: evcxr::runtime::Runtime::install_crash_handlers::segfault_handler
   3: _sigtramp
>> format!("{:02x}", 2)
Segmentation fault.
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: evcxr::runtime::Runtime::install_crash_handlers::segfault_handler
   3: _sigtramp
>> format!("{:x}", 3)
"656d6f5300000003"
```

LMK what other information I need to provide you.

Edit: Worth noting, this happens every time -- down to the exact string of garbage data I get the non-segfaulting lines.

**Comment by davidlattimore** [comment]
Thanks for the report. I tried adding those two lines to a test and then pushed it. The tests all passed, including on Mac. That's the only mechanism at my disposal to run stuff on a Mac. I'm not sure what version of the OS Travis is using. It says TARGET=x86_64-apple-darwin.

The only other thing I can think of to try is to clone the evcxr repository and run `cargo test` to see which tests fail. That might give us a clue as to what's wrong.

**Comment by thomcc** [comment]
This is the output of running tests your tests (along with the 2 I added whose source is below): https://gist.github.com/thomcc/fbcfe8696d8e9a831f7c51faf39731cf

The new test fails with assert triggers as essentially "2" != "656d6f5300000002", so I added two new tests the first of which (`format2`) always segfaults, and the 2nd (`format3`) always executes an illegal instruction.

Their source is included at the bottom of this comment.

Note that the existing tests question_mark_operator and function_panics_with_variable_preserving also cause signals too (first is sigbus, 2nd it's not clear from the output which). 

Everything is fine in v0.4.6, I'm going to do a git bisect and see if that tracks things down.

---

Source for the sigsegv and sigill triggering tests below. These were included at the end as to not mess up line numbers in the backtrace.

```rust
#[test]
fn format2() {
    let mut e = new_context();
    eval!(e, format!("{:02x}", 3));
}

#[test]
fn format3() {
    let mut e = new_context();
    eval!(e,
        assert_eq!(
            [1, 2, 3, 4, 5].iter()
                .map(|v| format!("{:x}", v))
                .collect::<Vec<_>>()
                .join(","),
            "1,2,3,4,5"
        );
    );
}
```

**Comment by thomcc** [comment]
git bisect says https://github.com/google/evcxr/commit/6f2de8f700f59fb3432cff58957166ea10a0eb7f is the commit responsible, and, using that knowledge, I can confirm that using LLD is the problem:

```
>> :linker system
linker: system

>> format!("{:02x}", 3)
"03"
>> :linker lld
linker: lld

>> format!("{:02x}", 3)
Segmentation fault.
stack backtrace:
   0: backtrace::backtrace::libunwind::trace::hf365ce9d28e99114 (0x10ed08c5d)
             at /Users/thom/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
      backtrace::backtrace::trace_unsynchronized::hf301d5725bdcf128
             at /Users/thom/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace::h1448e8ec713c0a03 (0x10ed08be3)
             at /Users/thom/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create::h87d33ca2de0a882a (0x10ecf88d7)
             at /Users/thom/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/capture.rs:163
   3: backtrace::capture::Backtrace::new::hf248074bc200e256 (0x10ecf87e6)
             at /Users/thom/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/capture.rs:127
   4: evcxr::runtime::Runtime::install_crash_handlers::segfault_handler::h8e7e72d9315f6dcb (0x10ec605d9)
             at evcxr/src/runtime.rs:107
   5: <unknown> (0x7fff6f7ecb5d)
Child process terminated with status: signal: 6
```

**Comment by davidlattimore** [comment]
Ah, interesting. Thanks for tracking that down! So I guess we should disable use of lld on mac.

**Comment by thomcc** [comment]
http://lists.llvm.org/pipermail/cfe-dev/2019-March/061666.html indicates that LLD on macos doesn't really work -- I have it installed as part of LLVM tools, but I think maybe you should use `system` by default for macs.
