### ISSUE TITLE
`:dep <crate name>` should use latest version of the crate

### ISSUE THREAD

**Issue by thomcc** [google/evcxr#97]
E.g. if you omit a version and such, it should automatically look up and use the latest version of the listed crate.

I don't think this is quite the same as having `:dep crate_name` be the same as `:dep crate_name = "*"`, but maybe it would be for the way `evcxr` runs code.

**Comment by davidlattimore** [comment]
Sounds like a nice ease-of-use thing. I'm not aware of any downsides to just treating it as ` = "*"`, but there could well be a downside I'm not aware of.
